import React, { useEffect, useState } from 'react'
import { useColorMode } from '@docusaurus/theme-common'

// The API reference index. Never point this at localhost: the on-load
// probe would trip Chrome's Local Network Access permission prompt
// ("access other apps and services on this device") for every visitor of
// a deployed site. Until kysely-apidoc deploys its Pagefind bundle, the
// probe fails and search runs guide-only.
const APIDOC_PAGEFIND_URL =
  'https://kysely-org.github.io/kysely-apidoc/pagefind/'

// Generated by `pnpm build`. In `docusaurus start` the dev server serves
// the last production build's bundle (see the pagefind-dev-server plugin
// in docusaurus.config.ts), so dev search works against stale content;
// with no build yet, the load fails and the stand-in button stays.
const SITE_PAGEFIND_URL = '/pagefind/'

declare global {
  interface Window {
    PagefindComponents?: {
      configureInstance: (instance: string, options: object) => void
    }
  }
}

declare module 'react' {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      'pagefind-modal-trigger': React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement>,
        HTMLElement
      > & {
        instance?: string
        placeholder?: string
        shortcut?: string
        compact?: boolean
      }
    }
  }
}

type PagefindModalElement = HTMLElement & { close?: () => void }

// A dead merged index is fatal: searches await it and hang, so an
// unreachable API docs origin (outage, or the bundle not deployed yet)
// would break every search. Probe before merging; when the probe fails,
// search runs guide-only.
let apidocIndexProbe: Promise<boolean> | undefined

function probeApidocIndex(): Promise<boolean> {
  apidocIndexProbe ??= fetch(`${APIDOC_PAGEFIND_URL}pagefind-entry.json`, {
    method: 'HEAD',
    signal: AbortSignal.timeout(2000),
  }).then(
    (response) => response.ok,
    () => false,
  )

  return apidocIndexProbe
}

let componentAssets: Promise<void> | undefined

function loadComponentAssets(): Promise<void> {
  componentAssets ??= new Promise((resolve, reject) => {
    const link = document.createElement('link')
    link.rel = 'stylesheet'
    link.href = `${SITE_PAGEFIND_URL}pagefind-component-ui.css`
    document.head.appendChild(link)

    const script = document.createElement('script')
    script.type = 'module'
    script.src = `${SITE_PAGEFIND_URL}pagefind-component-ui.js`
    script.onload = () => resolve()
    script.onerror = () =>
      reject(new Error('Failed to load Pagefind. Is this a production build?'))
    document.head.appendChild(script)
  })

  return componentAssets
}

// The modal lives OUTSIDE React, appended to document.body once and never
// unmounted: SPA navigations remount the navbar (and everything React
// renders in it), and the component registry keeps pointing at the first
// registered modal element. A React-managed modal detaches on remount and
// the next trigger click throws "showModal ... element is not in a
// Document" with the open-state stuck, freezing the page. Its DOM position
// is irrelevant, it renders in the browser's top layer.
let modalRoot: HTMLElement | undefined

function ensureModal(): void {
  if (modalRoot?.isConnected) {
    return
  }

  modalRoot = document.createElement('div')
  const modal = document.createElement('pagefind-modal') as PagefindModalElement
  modal.setAttribute('reset-on-close', '')
  modalRoot.appendChild(modal)
  document.body.appendChild(modalRoot)

  // The component's cleanup (deregistering shortcuts so the hints footer
  // doesn't keep a stale "navigate", plus the reset-on-close reset) only
  // runs on ITS close paths; a native dialog cancel closes behind its
  // back with partial state sync. Suppress the native cancel so Escape
  // always flows through the component's registered shortcut instead.
  const suppressedDialogs = new WeakSet<HTMLDialogElement>()

  const suppressNativeCancel = (root: ParentNode) => {
    const dialog =
      root instanceof HTMLDialogElement ? root : root.querySelector?.('dialog')
    if (dialog && !suppressedDialogs.has(dialog)) {
      suppressedDialogs.add(dialog)
      dialog.addEventListener('cancel', (event) => event.preventDefault())
    }
  }

  suppressNativeCancel(modal)

  // With the native cancel suppressed, Escape depends entirely on the
  // component's registered shortcut; if that ever misses, close through
  // the component's own close() a tick later. Either way cleanup
  // (handleClose) runs exactly once.
  document.addEventListener('keydown', (event) => {
    if (event.key !== 'Escape' || !modal.querySelector('dialog[open]')) {
      return
    }

    setTimeout(() => {
      if (modal.querySelector('dialog[open]')) {
        modal.close?.()
      }
    }, 0)
  })

  // Converge on every close, whichever path closed the dialog:
  // - the trigger's open-tracking, or its internal flag wedges "open" and
  //   further clicks no-op until refresh (query it fresh; it remounts
  //   with the navbar),
  // - the input, which doesn't sync from instance state while closed and
  //   pushes its stale value into a new search on reopen.
  const resetObserver = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (
        mutation.target instanceof HTMLDialogElement &&
        !mutation.target.open
      ) {
        document
          .querySelector<HTMLElement & { handleModalClose?: () => void }>(
            'pagefind-modal-trigger',
          )
          ?.handleModalClose?.()

        const searchInput = modal.querySelector('input')
        if (searchInput && searchInput.value !== '') {
          searchInput.value = ''
          searchInput.dispatchEvent(new Event('input', { bubbles: true }))
        }
      }
    }
  })

  resetObserver.observe(modal, {
    attributeFilter: ['open'],
    attributes: true,
    subtree: true,
  })

  // Source hints on result titles, rendered by CSS from this attribute.
  // API results live on another origin and additionally open in a new
  // tab. Results render lazily, so stamp links as they appear.
  const SECTION_BADGES: Record<string, string> = {
    examples: 'Example',
    integrations: 'Integration',
    recipes: 'Recipe',
  }

  const badgeFor = (link: HTMLAnchorElement): string | null => {
    const url = new URL(link.href, window.location.href)

    if (url.origin !== window.location.origin) {
      return 'API'
    }

    const section = url.pathname.match(/^\/docs\/([^/]+)\//)?.[1]
    return (section && SECTION_BADGES[section]) || null
  }

  const stampResultLinks = (root: ParentNode) => {
    for (const link of root.querySelectorAll?.('a[href]') ?? []) {
      if (!(link instanceof HTMLAnchorElement)) {
        continue
      }

      const badge = badgeFor(link)
      if (!badge) {
        continue
      }

      if (badge === 'API') {
        link.target = '_blank'
        link.rel = 'noopener'
      }

      link.setAttribute('data-result-badge', badge)

      // Examples get a secondary pill with their category, e.g. "where".
      // Rendered from the title element, since the link's ::after is
      // taken by the primary badge.
      if (badge === 'Example') {
        const category = new URL(
          link.href,
          window.location.href,
        ).pathname.split('/')[3]
        if (category) {
          link
            .closest('.pf-result-title')
            ?.setAttribute('data-result-badge-detail', category)
        }
      }
    }
  }

  const linkObserver = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      for (const node of mutation.addedNodes) {
        if (node instanceof Element) {
          stampResultLinks(node)
          suppressNativeCancel(node)
        }
      }
    }
  })

  stampResultLinks(modal)
  linkObserver.observe(modal, { childList: true, subtree: true })

  // Like pagefind.app: while the modal is open, the page scrollbar stays
  // rendered but scrolling is inert outside the modal. The component
  // doesn't do this itself. Keyed off the dialog's [open] attribute (DOM
  // truth), never off component state, which can go stale and would keep
  // the page frozen.
  const onScrollIntent = (event: Event) => {
    if (
      modal.querySelector('dialog[open]') &&
      (!(event.target instanceof Element) ||
        !event.target.closest('pagefind-modal'))
    ) {
      event.preventDefault()
    }
  }

  document.addEventListener('wheel', onScrollIntent, { passive: false })
  document.addEventListener('touchmove', onScrollIntent, { passive: false })
}

export default function SearchBar(): React.JSX.Element {
  const [isReady, setIsReady] = useState(false)
  // Rendered during SSR, so default to Mac and correct after mount.
  const [modifierKey, setModifierKey] = useState('⌘')
  const { colorMode } = useColorMode()

  useEffect(() => {
    if (!/mac/i.test(navigator.platform)) {
      setModifierKey('Ctrl')
    }
  }, [])

  // The modal sits outside React; sync the component's dark palette hook
  // with the site theme by hand.
  useEffect(() => {
    if (colorMode === 'dark') {
      modalRoot?.setAttribute('data-pf-theme', 'dark')
    } else {
      modalRoot?.removeAttribute('data-pf-theme')
    }
  }, [isReady, colorMode])

  useEffect(() => {
    let cancelled = false

    void Promise.all([loadComponentAssets(), probeApidocIndex()])
      .then(([, includeApidocIndex]) => {
        if (cancelled) {
          return
        }

        if (!includeApidocIndex) {
          console.warn(
            '[search] API docs index unreachable, searching guides only',
          )
        }

        // Must run before any component connects: a connected component
        // creates the instance with defaults and this call would be
        // ignored.
        window.PagefindComponents?.configureInstance('default', {
          bundlePath: SITE_PAGEFIND_URL,
          mergeIndex: includeApidocIndex
            ? [
                {
                  bundlePath: APIDOC_PAGEFIND_URL,
                  // Typedoc pages score ~16-20x higher raw than guide pages
                  // for shared terms (exact term in title + dense short
                  // pages), so this needs to be tiny for guides to rank
                  // first. Calibrated against real scores: 0.05 still let
                  // "insert" go all-API, 0.02 over-buried exact API-name
                  // matches. Queries with no guide coverage (e.g. "stream")
                  // still surface API results.
                  indexWeight: 0.03,
                },
              ]
            : [],
        })

        ensureModal()
        setIsReady(true)
      })
      .catch((error) => {
        console.warn('[search]', error)
      })

    return () => {
      cancelled = true
    }
  }, [])

  if (!isReady) {
    // Static stand-in during SSR and while the bundle loads; also what
    // `docusaurus start` shows, where no Pagefind bundle exists. Clones the
    // live trigger's markup so the swap is pixel-identical.
    return (
      <button aria-label="Search" className="pf-trigger-btn" type="button">
        <span aria-hidden="true" className="pf-trigger-icon" />
        <span className="pf-trigger-text">Search</span>
        <span aria-hidden="true" className="pf-trigger-shortcut">
          <span className="pf-trigger-key">{modifierKey}</span>
          <span className="pf-trigger-key">K</span>
        </span>
      </button>
    )
  }

  // Custom-element props must stay off the JSX: React 19 assigns known
  // properties directly, and these elements expose getter-only reflections
  // (setting `placeholder` throws). Defaults are right anyway.
  return <pagefind-modal-trigger />
}
