type ErrorMessage =
  'Your TypeScript version is too old. Please upgrade to >= 4.6.'
export type Kysely = ErrorMessage
export type sql = ErrorMessage
export type expressionBuilder = ErrorMessage
export type Expression = ErrorMessage
export type ColumnType = ErrorMessage
export type Generated = ErrorMessage
export type GeneratedAlways = ErrorMessage
export type JSONColumnType = ErrorMessage
export type Selectable = ErrorMessage
export type Insertable = ErrorMessage
export type Updateable = ErrorMessage
export type MysqlDialect = ErrorMessage
export type PostgresDialect = ErrorMessage
export type SqliteDialect = ErrorMessage
export type MssqlDialect = ErrorMessage
export type InferResult = ErrorMessage
export type CompiledQuery = ErrorMessage
export type UpdateResult = ErrorMessage
export type InsertResult = ErrorMessage
export type DeleteResult = ErrorMessage
export type MergeResult = ErrorMessage
