packages:
  - './site'
  - './test/cloudflare-workers'

# `postinstall` ignore list
ignoredBuiltDependencies:
  - core-js # site dependency
  - core-js-pure # site dependency
  - sharp # wrangler dependency

minimumReleaseAge: 1440 # install package versions that are at least 1 day old (in minutes).

# `postinstall` allow list
onlyBuiltDependencies:
  - better-sqlite3@12.4.1
  - esbuild@0.25.10
  - workerd@1.20251004.0 # wrangler dependency

trustPolicy: no-downgrade # fail if there's a regression in attestation of packages.

trustPolicyExclude:
  - langium@3.3.1 # mermaid@11.12.0 dependency - https://socket.dev/npm/package/langium/overview/3.3.1
  - semver@5.7.2 || 6.3.1 # tsd@0.20.0 || @docusaurus/core@3.9.1 - https://socket.dev/npm/package/semver/overview/5.7.2 || https://socket.dev/npm/package/semver/overview/6.3.1
