packages:
- './site'
- './test/cloudflare-workers'

# `postinstall` ignore list
ignoredBuiltDependencies:
- core-js # site dependency
- core-js-pure # site dependency
- sharp # wrangler dependency

# `postinstall` allow list
onlyBuiltDependencies:
- better-sqlite3
- esbuild
- workerd # wrangler dependency
