packages:
  - './site'
  - './test/cloudflare-workers'

# `postinstall` ignore list
ignoredBuiltDependencies:
  - core-js # site dependency
  - core-js-pure # site dependency
  - sharp # wrangler dependency

minimumReleaseAge: 1440 # install package versions that are at least 1 day old (in minutes).

# `postinstall` allow list
onlyBuiltDependencies:
  - better-sqlite3@12.4.1
  - esbuild@0.25.10
  - workerd@1.20251004.0 # wrangler dependency

overrides:
  chokidar: 4.0.1 # mocha dependency. versions 4.0.2 & 4.0.3 fail trust policy

trustPolicy: no-downgrade # fail if there's a regression in attestation of packages.
