packages:
  - './site'
  - './test/cloudflare-workers'

# Allow (true) or disallow (false) script execution.
# https://pnpm.io/settings#allowbuilds
allowBuilds:
  better-sqlite3@12.10.0: true
  core-js: false # site dependency, useless scripts
  core-js-pure: false # site dependency, useless scripts
  esbuild@0.27.3 || 0.28.0: true # tsx@4.21.0 dependency || direct.
  sharp: false # wrangler dependency, useless scripts
  workerd@1.20260504.1: true # wrangler@4.88.0 dependency

auditConfig:
  # Don't show in `pnpm audit`.
  # https://pnpm.io/cli/audit#auditconfigignoreghsas
  ignoreGhsas:
    - GHSA-h726-x36v-rx45 # prototype-pollution-vulnerable-lodash.merge-dont-upgrade

# Deduplicate peer dependencies.
# see: https://github.com/pnpm/pnpm/issues/11070
dedupePeers: true

# Deny package installs that don't match the supported Node.js version/s.
# https://pnpm.io/settings#enginestrict
engineStrict: true

# avoid having to use `-w` when installing packages at project root.
# https://pnpm.io/settings#ignoreworkspacerootcheck
ignoreWorkspaceRootCheck: true

# fail and don't fallback to "too new" version of packages when none of their other
# versions match `minimumReleaseAge` range (default is 1 day).
# https://pnpm.io/settings#minimumreleaseagestrict
minimumReleaseAgeStrict: true

# how versions get prefixed in `package.json`.
# https://pnpm.io/settings#saveprefix
savePrefix: ''

# Fail if a package's trust level has decreased compared to previous releases.
# https://pnpm.io/settings#trustpolicy
trustPolicy: no-downgrade

# A list of package selectors that should be excluded from the trust policy check.
# https://pnpm.io/settings#trustpolicyexclude
trustPolicyExclude:
  - semver@5.7.2 || 6.3.1 # tsd@0.20.0 || @docusaurus/core@3.10.0 dependency - https://socket.dev/npm/package/semver/overview/5.7.2 || https://socket.dev/npm/package/semver/overview/6.3.1

updateConfig:
  # Don't show in `pnpm outdated` or update in `pnpm update`.
  # https://pnpm.io/settings#updateconfigignoredependencies
  ignoreDependencies:
    - '@types/prototype-pollution-vulnerable-lodash.merge-dont-upgrade'
    - 'prototype-pollution-vulnerable-lodash.merge-dont-upgrade'

# Prompt before running custom scripts if `node_modules` is out of date.
# https://pnpm.io/settings#verifydepsbeforerun
verifyDepsBeforeRun: prompt
