export type OperationNodeKind =
  | 'IdentifierNode'
  | 'QueryNode'
  | 'RawNode'
  | 'SelectNode'
  | 'SelectionNode'
  | 'ReferenceNode'
  | 'ColumnNode'
  | 'TableNode'
  | 'AliasNode'
  | 'FromNode'
  | 'SelectAllNode'
  | 'FilterNode'
  | 'AndNode'
  | 'OrNode'
  | 'ParensNode'
  | 'ValueNode'
  | 'ValueListNode'
  | 'PrimitiveValueListNode'
  | 'JoinNode'
  | 'OperatorNode'
  | 'WhereNode'
  | 'InsertNode'
  | 'DeleteNode'
  | 'ReturningNode'
  | 'CreateTableNode'
  | 'ColumnDefinitionNode'
  | 'DropTableNode'
  | 'DataTypeNode'

export interface OperationNode {
  readonly kind: OperationNodeKind
}
