import { Generated, GeneratedAlways, ColumnType } from '../../dist/cjs'

export interface Pet {
  id: Generated<string>
  name: string
  owner_id: number
  species: 'dog' | 'cat'
}

export interface Toy {
  id: Generated<string>
  price: number
  pet_id: string
}

export interface Movie {
  id: Generated<string>
  stars: number
}

export interface Book {
  id: GeneratedAlways<number>
  name: string
}

export interface Database {
  person: Person
  pet: Pet
  movie: Movie
  'some_schema.movie': Movie
  book: Book
  toy: Toy
  person_metadata: PersonMetadata
}

export interface Person {
  id: Generated<number>
  first_name: string
  last_name: string | null
  age: number
  gender: 'male' | 'female' | 'other'
  marital_status: 'single' | 'married' | 'divorced' | 'widowed' | null
  // A Column that is generated by the DB and which
  // we never want the user to be able to insert or
  // update.
  modified_at: ColumnType<Date, never, never>
}

export interface PersonMetadata {
  id: Generated<number>
  person_id: number
  website: ColumnType<{ url: string }, string, string>
  nicknames: ColumnType<string[], string, string>
  profile: ColumnType<
    {
      auth: {
        roles: string[]
        last_login?: { device: string }
      }
      tags: string[]
    },
    string,
    string
  >
  experience: ColumnType<
    {
      establishment: string
    }[],
    string,
    string
  >
  schedule: ColumnType<{ name: string; time: string }[][][], string, string>
}
