name: preview

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/*'
      - '!.github/workflows/*.yml'
      - '.github/workflows/preview.yml'
      - '!assets/**'
      - '!docs/**'
      - '!example/**'
      - '!site/**'
      - '!test/**'
      - '!.node-version'
      - '!.nvmrc'
      - '!.prettierignore'
      - '!.prettierrc.json'
      - '!*.md'
      - '!deno.check*'
      - '!deno.lint.json'
      - '!docker-compose.yml'
      - '!jsr.json'
      - '!LICENSE'

jobs:
  release:
    name: Release preview build
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: 'pnpm'
          node-version: lts/*

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Release preview version
        run: pnpx pkg-pr-new@0.0.61 publish --template './example'
