name: secure

on:
  push:
    branches: [master, next]
  pull_request:
    branches: ['**']

permissions: {}

jobs:
  node:
    concurrency:
      cancel-in-progress: ${{ github.ref_name != 'master' }}
      group: ${{ github.workflow }}-node-${{ github.event.pull_request.number || github.sha }}

    name: Audit Node.js dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true

      - name: use node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*

      - name: audit dependencies
        run: pnpm audit

  zizmor:
    concurrency:
      cancel-in-progress: ${{ github.ref_name != 'master' }}
      group: ${{ github.workflow }}-zizmor-${{ github.event.pull_request.number || github.sha }}

    name: zizmor github actions scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
        with:
          advanced-security: false
          annotations: true
          persona: pedantic
